module.exports = {
  POST_SPLASH: "POST_SPLASH",
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  HOME: "HOME",
  PASSWORD_RECOVERY: "PASSWORD_RECOVERY",
  PENDING_REGISTER_VALIDATION: "PENDING_REGISTER_VALIDATION",
}
