const screens = {
	POST_SPLASH: "POST_SPLASH",
	REGISTER: "REGISTER",
	LOGIN: "LOGIN",
	LOGIN_ADMIN: "LOGIN_ADMIN",
	PASSWORD_RECOVERY_ADMIN:"PASSWORD_RECOVERY_ADMIN",
	HOME: "HOME",
	HOME_ADMIN: "HOME_ADMIN",
	PASSWORD_RECOVERY: "PASSWORD_RECOVERY",
	PENDING_REGISTER_VALIDATION: "PENDING_REGISTER_VALIDATION",
	NEW_ORDER: "NEW_ORDER",
	ORDER_DETAILS: "ORDER_DETAILS",
	PROFILE: "PROFILE",
	PASSWORD_UPDATE: "PASSWORD_UPDATE",
	NEW_ORDER_STEP_1: "NEW_ORDER_STEP_1",
	NEW_ORDER_STEP_2: "NEW_ORDER_STEP_2",
	NEW_ORDER_STEP_3: "NEW_ORDER_STEP_3",
	NEW_ORDER_STEP_3_MAP: "NEW_ORDER_STEP_3_MAP",
	NEW_ORDER_STEP_4: "NEW_ORDER_STEP_4",
	NEW_ORDER_PLACED: "NEW_ORDER_PLACED",
	FAQ: "FAQ",
	CREATE_USER:"CREATE_USER",
	UPDATE_USER:"UPDATE_USER",
	ASSIGN_ORDER_TO:"ASSIGN_ORDER_TO"
};

export default screens;